// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class AccountGoals
    {
        [Key]
        public int Id { get; set; }
        [StringLength(200)]
        public string EventName { get; set; }
        public string EventRule { get; set; }
        [StringLength(5)]
        public string Language { get; set; }
        [Column("EventNameJSON")]
        public string EventNameJson { get; set; }
        public int? CountryId { get; set; }
        public int? PricePoint { get; set; }
        public bool? IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StartedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndDate { get; set; }
        public int? TableOrder { get; set; }
        public string Image { get; set; }
    }
}