// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class AccountDevicesInsertResult
    {
        public long Id { get; set; }
        public long AccountId { get; set; }
        public string IP { get; set; }
        public string AccountAgent { get; set; }
        public string DeviceName { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CountryId { get; set; }
    }
}
