// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class AccountErrorsInsertResult
    {
        public long Id { get; set; }
        public long AccountId { get; set; }
        public DateTime? EventDate { get; set; }
        public string ErrorUrl { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorDescription { get; set; }
        public string IP { get; set; }
        public string AccountAgent { get; set; }
        public int? ErrorType { get; set; }
        public string Language { get; set; }
    }
}
