// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class AccountSearchHistory
    {
        [Key]
        public long Id { get; set; }
        public long AccountId { get; set; }
        public string Key { get; set; }
        [StringLength(300)]
        public string Location { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(5)]
        public string Language { get; set; }
        public long AccountDeviceId { get; set; }
    }
}