// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class AccountWalletRequestsInsertResult
    {
        public long Id { get; set; }
        public long AccountId { get; set; }
        public DateTime? RequestDate { get; set; }
        public int? TransferType { get; set; }
        public int? CountryId { get; set; }
        public decimal? RequestedAmount { get; set; }
        public decimal? CommissionRate { get; set; }
        public bool? SendNotification { get; set; }
        public bool? HasCompleted { get; set; }
        public DateTime? CompletedDate { get; set; }
        public int? RequestedAmountCurrency { get; set; }
        public string GoogleClientId { get; set; }
        public string IPAddress { get; set; }
        public string SessionInfo { get; set; }
        public string AccountAgent { get; set; }
        public long AccountDeviceId { get; set; }
    }
}
