// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class AccountErrors
    {
        [Key]
        public long Id { get; set; }
        public long AccountId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EventDate { get; set; }
        [StringLength(200)]
        public string ErrorUrl { get; set; }
        [StringLength(50)]
        public string ErrorCode { get; set; }
        public string ErrorDescription { get; set; }
        [Column("IP")]
        [StringLength(50)]
        public string Ip { get; set; }
        public string AccountAgent { get; set; }
        public int? ErrorType { get; set; }
        [StringLength(3)]
        public string Language { get; set; }
    }
}