// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    [Keyless]
    public partial class AccountDetail
    {
        public long Id { get; set; }
        [StringLength(200)]
        public string Name { get; set; }
        [StringLength(200)]
        public string Surname { get; set; }
        [StringLength(200)]
        public string AccountIcon { get; set; }
        [StringLength(200)]
        public string AccountName { get; set; }
        public bool? IsVerified { get; set; }
        [StringLength(5)]
        public string Language { get; set; }
        public bool? IsDeleted { get; set; }
        public Guid? Guid { get; set; }
        public string PersonelInfo { get; set; }
        [StringLength(300)]
        public string Location { get; set; }
        [StringLength(300)]
        public string Website { get; set; }
        [StringLength(200)]
        public string CoverImage { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        public bool? HasSentNotifyOnComment { get; set; }
        [StringLength(300)]
        public string Title { get; set; }
        [StringLength(200)]
        public string Password { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Birthday { get; set; }
        [StringLength(20)]
        public string PhoneNumber { get; set; }
        [StringLength(200)]
        public string Email { get; set; }
        public int? Currency { get; set; }
        [StringLength(200)]
        public string GoogleId { get; set; }
        [StringLength(200)]
        public string AppleId { get; set; }
        public int? CountryId { get; set; }
        public long? ProfileViewCount { get; set; }
        public long? PostViewCount { get; set; }
        public long? FollowCount { get; set; }
        public long? FollowerCount { get; set; }
        public long? CommentCount { get; set; }
        public long? PostLikedCount { get; set; }
        public long? PostBlockedCount { get; set; }
        public long? ProfileBlockedCount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastScanDate { get; set; }
        public int? PostCountThisWeek { get; set; }
        public int? FollowerCountThisWeek { get; set; }
        public long? ViewCountThisWeek { get; set; }
        [StringLength(50)]
        public string EarningThisMounth { get; set; }
    }
}