// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class AccountProfileEncryptedInsertResult
    {
        public long Id { get; set; }
        public long AccountId { get; set; }
        public string Password { get; set; }
        public DateTime? Birthday { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public int? Currency { get; set; }
        public string GoogleId { get; set; }
        public string AppleId { get; set; }
        public int? CountryId { get; set; }
    }
}
