// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class AccountWalletEvents
    {
        [Key]
        public long Id { get; set; }
        public long AccountId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EventDate { get; set; }
        [Column(TypeName = "decimal(19, 2)")]
        public decimal? EarningPrice { get; set; }
        public long? PostId { get; set; }
        public int? CurrencyType { get; set; }
        public string Url { get; set; }
    }
}