// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class AccountProfileStyleUpdateResult
    {
        public long Id { get; set; }
        public long AccountId { get; set; }
        public string FontSizeOnArticle { get; set; }
        public string GridSize { get; set; }
        public string BackgroudColor { get; set; }
        public bool? IsLTR { get; set; }
        public string H1Style { get; set; }
        public string UrlStyle { get; set; }
        public bool? HideAdvertorial { get; set; }
    }
}
