// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class AccountsRecommendedTagsForMeResult
    {
        public long Id { get; set; }
        public long LikedPostId { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string PostContent { get; set; }
        public string PostTitle { get; set; }
        public int? PostType { get; set; }
        public string Language { get; set; }
        public long AuthorId { get; set; }
    }
}
