// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class AccountActionsGetByIDResult
    {
        public long Id { get; set; }
        public string GoogleClientId { get; set; }
        public long AccountId { get; set; }
        public long? PostId { get; set; }
        public long? ProfileId { get; set; }
        public string VisitedUrl { get; set; }
        public long? TagId { get; set; }
        public bool? OnProfile { get; set; }
        public string ClickedElements { get; set; }
        public string SessionId { get; set; }
        public string ReferalFrom { get; set; }
        public DateTime? EventDate { get; set; }
    }
}
