// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class AccountNewsletterInfo
    {
        [Key]
        public int Id { get; set; }
        public long AccountId { get; set; }
        public int? MailFrequency { get; set; }
        public int? NotifyType { get; set; }
        [StringLength(100)]
        public string NewsletterMail { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
    }
}