// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class AccountProfileStyle
    {
        [Key]
        public long Id { get; set; }
        public long AccountId { get; set; }
        [StringLength(10)]
        public string FontSizeOnArticle { get; set; }
        [StringLength(10)]
        public string GridSize { get; set; }
        [StringLength(10)]
        public string BackgroudColor { get; set; }
        [Column("IsLTR")]
        public bool? IsLtr { get; set; }
        [Column("H1Style")]
        public string H1style { get; set; }
        [StringLength(200)]
        public string UrlStyle { get; set; }
        public bool? HideAdvertorial { get; set; }
    }
}