// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class AccountTokensInsertResult
    {
        public long Id { get; set; }
        public long AccountId { get; set; }
        public string ClientId { get; set; }
        public string SecretKey { get; set; }
        public string Token { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ExpirationDate { get; set; }
        public string AccountAgent { get; set; }
        public string IP { get; set; }
        public long? AccountDeviceId { get; set; }
    }
}
