// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class AccountActions
    {
        [Key]
        public long Id { get; set; }
        [StringLength(50)]
        public string GoogleClientId { get; set; }
        [Key]
        public long AccountId { get; set; }
        public long? PostId { get; set; }
        public long? ProfileId { get; set; }
        public string VisitedUrl { get; set; }
        public long? TagId { get; set; }
        public bool? OnProfile { get; set; }
        public string ClickedElements { get; set; }
        [StringLength(200)]
        public string SessionId { get; set; }
        public string ReferalFrom { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EventDate { get; set; }
    }
}