// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class ActivisionCodesUpdateResult
    {
        public long Id { get; set; }
        public string ActivisionCode { get; set; }
        public long AccountId { get; set; }
        public DateTime? LastValidDate { get; set; }
        public DateTime? CreatedDate { get; set; }
        public bool? IsApproved { get; set; }
    }
}
