// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class ActivisionCodes
    {
        [Key]
        public long Id { get; set; }
        [StringLength(200)]
        public string ActivisionCode { get; set; }
        public long AccountId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastValidDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        public bool? IsApproved { get; set; }
    }
}