// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class Advertorials
    {
        [Key]
        public long Id { get; set; }
        public string Name { get; set; }
        public int AdvertorialTypeId { get; set; }
        public int AdvertorialPositionId { get; set; }
        public string AdvImg { get; set; }
        public string AdvContent { get; set; }
        [StringLength(200)]
        public string ButtonText { get; set; }
        [StringLength(5)]
        public string Language { get; set; }
        public int? TableOrder { get; set; }
        public string Url { get; set; }
        [StringLength(200)]
        public string Image { get; set; }
        [StringLength(10)]
        public string Width { get; set; }
        [StringLength(10)]
        public string Height { get; set; }
        public string InlineStyles { get; set; }
        public string InlineScripts { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FinishDate { get; set; }
        public bool? IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
    }
}