// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class AdvertorialsInsertResult
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public int AdvertorialTypeId { get; set; }
        public int AdvertorialPositionId { get; set; }
        public string AdvImg { get; set; }
        public string AdvContent { get; set; }
        public string ButtonText { get; set; }
        public string Language { get; set; }
        public int? TableOrder { get; set; }
        public string Url { get; set; }
        public string Image { get; set; }
        public string Width { get; set; }
        public string Height { get; set; }
        public string InlineStyles { get; set; }
        public string InlineScripts { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? FinishDate { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
    }
}
