// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    [Table("BlockedIPs")]
    public partial class BlockedIps
    {
        [Key]
        public long Id { get; set; }
        [Column("IPAddress")]
        [StringLength(50)]
        public string Ipaddress { get; set; }
        public string AccountAgent { get; set; }
        [StringLength(50)]
        public string Location { get; set; }
        public long? ReferalAccountId { get; set; }
        public int BlockedTypeId { get; set; }
        public bool? IsBlockedAllready { get; set; }
    }
}