// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class BlockedIPsGetAllResult
    {
        public long Id { get; set; }
        public string IPAddress { get; set; }
        public string AccountAgent { get; set; }
        public string Location { get; set; }
        public long? ReferalAccountId { get; set; }
        public int BlockedTypeId { get; set; }
        public bool? IsBlockedAllready { get; set; }
    }
}
