// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class ContentsGetByIDResult
    {
        public int Id { get; set; }
        public string Language { get; set; }
        public bool? WillOutOfSite { get; set; }
        public string RedirectUrl { get; set; }
        public string GroupName { get; set; }
        public int? Positions { get; set; }
        public string PageContent { get; set; }
        public string PageContentJSON { get; set; }
        public string PageTitle { get; set; }
        public string PageTitleJSON { get; set; }
        public int? TableOrder { get; set; }
        public int? ParentId { get; set; }
        public string Url { get; set; }
        public bool? IsAccessible { get; set; }
    }
}
