// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class ContentAccordions
    {
        [Key]
        public int Id { get; set; }
        public int ContentId { get; set; }
        public bool? IsPublished { get; set; }
        [StringLength(5)]
        public string Language { get; set; }
        public int? TableOrder { get; set; }
        public string Answer { get; set; }
        public string Question { get; set; }
    }
}