// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class Contents
    {
        [Key]
        public int Id { get; set; }
        [StringLength(5)]
        public string Language { get; set; }
        public bool? WillOutOfSite { get; set; }
        [StringLength(400)]
        public string RedirectUrl { get; set; }
        [StringLength(200)]
        public string GroupName { get; set; }
        public int? Positions { get; set; }
        public string PageContent { get; set; }
        [Column("PageContentJSON")]
        public string PageContentJson { get; set; }
        [StringLength(200)]
        public string PageTitle { get; set; }
        [Column("PageTitleJSON")]
        [StringLength(200)]
        public string PageTitleJson { get; set; }
        public int? TableOrder { get; set; }
        public int? ParentId { get; set; }
        public string Url { get; set; }
        public bool? IsAccessible { get; set; }
    }
}