// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class CountryGetAllResult
    {
        public int Id { get; set; }
        public string ShortName { get; set; }
        public string Name { get; set; }
        public int? PreferredLanguage { get; set; }
        public string NameJSON { get; set; }
        public int? ContinentId { get; set; }
        public string CoordinateRange { get; set; }
        public int? Capital { get; set; }
        public string PreferredLanguageStr { get; set; }
    }
}
