// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class Country
    {
        [Key]
        public int Id { get; set; }
        [StringLength(5)]
        public string ShortName { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        public int? PreferredLanguage { get; set; }
        [Column("NameJSON")]
        public string NameJson { get; set; }
        public int? ContinentId { get; set; }
        public string CoordinateRange { get; set; }
        public int? Capital { get; set; }
        [StringLength(5)]
        public string PreferredLanguageStr { get; set; }
    }
}