// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class DynamicTableForeignKeysGenResult
    {
        public string table_schema_name { get; set; }
        public string table_name { get; set; }
        public string column_name { get; set; }
        public string constraint_name { get; set; }
        public string primary_table_schema_name { get; set; }
        public string primary_table_name { get; set; }
        public string primary_table_column { get; set; }
        public string join_condition { get; set; }
        public string complex_fk { get; set; }
        public int fk_part { get; set; }
    }
}
