// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class DynamicViewDTOGenResult
    {
        public string schema_name { get; set; }
        public string view_name { get; set; }
        public string column_name { get; set; }
        public string data_type { get; set; }
        public string data_type_ext { get; set; }
        public string nullable { get; set; }
        public object comments { get; set; }
    }
}
