// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class DynamicTableSearchAllGenResult
    {
        public string PrimaryKey { get; set; }
        public string ColumnName { get; set; }
        public string ColumnValue { get; set; }
    }
}
