// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class DynamicTableReportGenResult
    {
        public string schema_name { get; set; }
        public string table_name { get; set; }
        public DateTime created { get; set; }
        public DateTime last_modified { get; set; }
        public long? num_rows { get; set; }
        public object comments { get; set; }
    }
}
