// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class GetAccessControlResult
    {
        public string Name { get; set; }
        public int ID { get; set; }
        public bool? IsSystemObject { get; set; }
        public bool? IsAccessible { get; set; }
    }
}
