// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class GetIndexStatsResult
    {
        public string Database { get; set; }
        public string Table { get; set; }
        [Column("Index Name")]
        public string IndexName { get; set; }
        [Column("Index Type")]
        public string IndexType { get; set; }
        [Column("Avg Frag %")]
        public decimal? AvgFrag { get; set; }
        [Column("Row Ct")]
        public long? RowCt { get; set; }
        [Column("Stats Dt")]
        public string StatsDt { get; set; }
    }
}
