// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class GetIdentityListResult
    {
        public string table_schema { get; set; }
        public string table_name { get; set; }
        public string column_Name { get; set; }
    }
}
