// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class GetRequestParameterNamesResult
    {
        public string SPECIFIC_SCHEMA { get; set; }
        public string SPECIFIC_NAME { get; set; }
        public int ORDINAL_POSITION { get; set; }
        public string ROUTINE_TYPE { get; set; }
        public string RoutineResultDataType { get; set; }
        public string PARAMETER_NAME { get; set; }
        public int? ParameterDirection { get; set; }
        public string DDL_NAME { get; set; }
        public string TableDataType { get; set; }
    }
}
