// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class GetReturnParameterNamesResult
    {
        public string name { get; set; }
        public string system_type_name { get; set; }
        public bool? is_identity_column { get; set; }
    }
}
