// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class GetViewBackupHistoryResult
    {
        public string destination_database_name { get; set; }
        public DateTime? restore_date { get; set; }
        public DateTime? backup_start_date { get; set; }
        public DateTime? backup_finish_date { get; set; }
        public string source_database_name { get; set; }
        public string backup_file_used_for_restore { get; set; }
    }
}
