// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class GetViewListResult
    {
        public string view_schema { get; set; }
        public string view_name { get; set; }
        public string view_definition { get; set; }
    }
}
