// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class Language
    {
        [Key]
        public int Id { get; set; }
        [StringLength(200)]
        public string Name { get; set; }
        [StringLength(200)]
        public string ShortCode { get; set; }
        public int? TableOrder { get; set; }
        public string Settings { get; set; }
        [StringLength(200)]
        public string Culture { get; set; }
        [Column("FlagICON")]
        [StringLength(200)]
        public string FlagIcon { get; set; }
        [Column("NameJSON")]
        public string NameJson { get; set; }
        [StringLength(5)]
        public string UiCode { get; set; }
    }
}