// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class LanguageGetAllResult
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortCode { get; set; }
        public int? TableOrder { get; set; }
        public string Settings { get; set; }
        public string Culture { get; set; }
        public string FlagICON { get; set; }
        public string NameJSON { get; set; }
        public string UiCode { get; set; }
    }
}
