// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class NotificationPlans
    {
        [Key]
        public long Id { get; set; }
        public long? AccountId { get; set; }
        public long? TriggerAuthorId { get; set; }
        public int? AuthorActionId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        public bool? IsActive { get; set; }
        [StringLength(50)]
        public string PreferredNotifyTypes { get; set; }
    }
}