// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class PostSettingsGetAllResult
    {
        public long Id { get; set; }
        public long PostId { get; set; }
        public bool? HasSentNotifyOnComment { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public bool? IsOpenToComment { get; set; }
        public DateTime? PublishedDate { get; set; }
        public bool? IsDeleted { get; set; }
        public bool? IsPrivate { get; set; }
        public bool? IsStatu { get; set; }
        public string Url { get; set; }
        public string PostTags { get; set; }
        public string PostCategory { get; set; }
    }
}
