// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class Posts
    {
        [Key]
        public long Id { get; set; }
        [StringLength(200)]
        public string PostTitle { get; set; }
        public string PostContent { get; set; }
        public bool? IsViewable { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(200)]
        public string CoverPhoto { get; set; }
        public int? PostType { get; set; }
        [StringLength(5)]
        public string Language { get; set; }
        public long AccountId { get; set; }
        public long? PostId { get; set; }
        public Guid? Guid { get; set; }
    }
}