// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class PostsDetailListPagerWithLangResult5
    {
        public long Id { get; set; }
        public string PostTitle { get; set; }
        public string PostContent { get; set; }
        public bool? IsViewable { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CoverPhoto { get; set; }
        public int? PostType { get; set; }
        public string Language { get; set; }
        public long AccountId { get; set; }
        public long? PostId { get; set; }
        public Guid? Guid { get; set; }
        public int? TotalRows { get; set; }
    }
}
