// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class PostCategoryGetAllResult
    {
        public int Id { get; set; }
        public int? CategoryId { get; set; }
        public string Language { get; set; }
        public string Name { get; set; }
    }
}
