// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class PostsByTagByLangResult
    {
        public Guid? Guid { get; set; }
        public string PostTitle { get; set; }
        public string PostContent { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CoverPhoto { get; set; }
        public int? PostType { get; set; }
        public long? ViewCount { get; set; }
        public long? LikeCount { get; set; }
        public long? ShareToolClickCount { get; set; }
        public bool? IsNews { get; set; }
        public bool? IsPopular { get; set; }
        public bool? IsTrend { get; set; }
        public DateTime? LastScanDate { get; set; }
        public int? CommentCount { get; set; }
    }
}
