// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class ProcedureLogUpdateResult
    {
        public DateTime LogDate { get; set; }
        public int? DatabaseID { get; set; }
        public int? ObjectID { get; set; }
        public string ProcedureName { get; set; }
        public int? ErrorLine { get; set; }
        public string ErrorMessage { get; set; }
        public string AdditionalInfo { get; set; }
    }
}
