// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    [Keyless]
    public partial class ProcedureLog
    {
        [Column(TypeName = "smalldatetime")]
        public DateTime LogDate { get; set; }
        [Column("DatabaseID")]
        public int? DatabaseId { get; set; }
        [Column("ObjectID")]
        public int? ObjectId { get; set; }
        [StringLength(400)]
        public string ProcedureName { get; set; }
        public int? ErrorLine { get; set; }
        public string ErrorMessage { get; set; }
        public string AdditionalInfo { get; set; }
    }
}