// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class RecordAttributes
    {
        [Key]
        public int Id { get; set; }
        [Column("RecordID")]
        public int RecordId { get; set; }
        [Required]
        public string JsonAttributes { get; set; }
    }
}