// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class ReportsInsertResult
    {
        public long Id { get; set; }
        public long? AccountId { get; set; }
        public long? AuthorId { get; set; }
        public int? PostId { get; set; }
        public int? ReportCauseId { get; set; }
        public string Result { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string Message { get; set; }
    }
}
