// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class Reports
    {
        [Key]
        public long Id { get; set; }
        public long? AccountId { get; set; }
        public long? AuthorId { get; set; }
        public int? PostId { get; set; }
        public int? ReportCauseId { get; set; }
        public string Result { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        public string Message { get; set; }
    }
}