// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class Resources
    {
        [Key]
        public int Id { get; set; }
        [StringLength(100)]
        public string KeyName { get; set; }
        public int? Language { get; set; }
        [Column("IsRTL")]
        public bool? IsRtl { get; set; }
        public string Translation { get; set; }
        [StringLength(2)]
        public string Statu { get; set; }
    }
}