// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class SocialMediaConnectionsGetByIDResult
    {
        public int Id { get; set; }
        public string SocialMedia { get; set; }
        public string ReverseIcon { get; set; }
        public int? TableOrder { get; set; }
        public string Url { get; set; }
        public string Icon { get; set; }
    }
}
