// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    [Keyless]
    public partial class SqlCatchLogs
    {
        [StringLength(50)]
        public string FuncName { get; set; }
        public int? Error { get; set; }
        public string Message { get; set; }
        [Column("XState")]
        public int? Xstate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
        [StringLength(50)]
        public string MachineName { get; set; }
        [StringLength(50)]
        public string LocalAddress { get; set; }
    }
}