// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class SqlCatchLogsUpdateResult
    {
        public string FuncName { get; set; }
        public int? Error { get; set; }
        public string Message { get; set; }
        public int? XState { get; set; }
        public DateTime? Date { get; set; }
        public string MachineName { get; set; }
        public string LocalAddress { get; set; }
    }
}
