// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WordyWellHero.Infrastructure.ReverserMigration
{
    public partial class Tags
    {
        [Key]
        public long Id { get; set; }
        public long CreatedByAdminAccount { get; set; }
        public long CreatedByAccount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(200)]
        public string Name { get; set; }
        [StringLength(5)]
        public string Language { get; set; }
        public long? ParentTagId { get; set; }
        public bool? IsBlocked { get; set; }
    }
}