using System;
using System.Net;
using System.Data;
using System.Linq;
using Microsoft.Data.SqlClient;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;

using Microsoft.AspNetCore.OData.Query;
using Microsoft.AspNetCore.OData.Routing.Controllers;
using Microsoft.AspNetCore.OData.Results;
using Microsoft.AspNetCore.OData.Deltas;
using Microsoft.AspNetCore.OData.Formatter;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace ZarenUI.Server.Controllers.JSONServer
{
    public partial class DesignSchemesInsertsController : ODataController
    {
        private ZarenUI.Server.Data.JSONServerContext context;

        public DesignSchemesInsertsController(ZarenUI.Server.Data.JSONServerContext context)
        {
            this.context = context;
        }


        [HttpGet]
        [EnableQuery(MaxExpansionDepth=10,MaxAnyAllExpressionDepth=10,MaxNodeCount=1000)]
        [Route("odata/JSONServer/DesignSchemesInsertsFunc(colors_body_background={colors_body_background},colors_body_font={colors_body_font},colors_body_font_size={colors_body_font_size},colors_body_font_color={colors_body_font_color},colors_content_text_color={colors_content_text_color},colors_content_border_color={colors_content_border_color},colors_content_background={colors_content_background},colors_content_padding={colors_content_padding},colors_content_margin={colors_content_margin},colors_menu_padding={colors_menu_padding},colors_menu_font_size={colors_menu_font_size},colors_menu_background={colors_menu_background},colors_menu_margin={colors_menu_margin},colors_header_padding={colors_header_padding},colors_header_font_size={colors_header_font_size},colors_header_background={colors_header_background},colors_header_margin={colors_header_margin},colors_footer_padding={colors_footer_padding},colors_footer_font_size={colors_footer_font_size},colors_footer_background={colors_footer_background},colors_footer_margin={colors_footer_margin},colors_wrapper_padding={colors_wrapper_padding},colors_wrapper_font_size={colors_wrapper_font_size},colors_wrapper_background={colors_wrapper_background},colors_wrapper_margin={colors_wrapper_margin},colors_group={colors_group},colors_color1_rgb={colors_color1_rgb},colors_color1_brightness={colors_color1_brightness},colors_color1_isDark={colors_color1_isDark},colors_color2_hex={colors_color2_hex},colors_color2_rgb={colors_color2_rgb},colors_color2_brightness={colors_color2_brightness},colors_color2_isDark={colors_color2_isDark},colors_color3_hex={colors_color3_hex},colors_color3_rgb={colors_color3_rgb},colors_color3_brightness={colors_color3_brightness},colors_color3_isDark={colors_color3_isDark},colors_color4_hex={colors_color4_hex},colors_color4_rgb={colors_color4_rgb},colors_color4_brightness={colors_color4_brightness},colors_color4_isDark={colors_color4_isDark},colors_color5_hex={colors_color5_hex},colors_color5_rgb={colors_color5_rgb},colors_color5_brightness={colors_color5_brightness},colors_color5_isDark={colors_color5_isDark})")]
        public IActionResult DesignSchemesInsertsFunc([FromODataUri] string colors_body_background, [FromODataUri] string colors_body_font, [FromODataUri] int? colors_body_font_size, [FromODataUri] string colors_body_font_color, [FromODataUri] string colors_content_text_color, [FromODataUri] string colors_content_border_color, [FromODataUri] string colors_content_background, [FromODataUri] string colors_content_padding, [FromODataUri] string colors_content_margin, [FromODataUri] string colors_menu_padding, [FromODataUri] int? colors_menu_font_size, [FromODataUri] string colors_menu_background, [FromODataUri] string colors_menu_margin, [FromODataUri] string colors_header_padding, [FromODataUri] int? colors_header_font_size, [FromODataUri] string colors_header_background, [FromODataUri] string colors_header_margin, [FromODataUri] string colors_footer_padding, [FromODataUri] int? colors_footer_font_size, [FromODataUri] string colors_footer_background, [FromODataUri] string colors_footer_margin, [FromODataUri] string colors_wrapper_padding, [FromODataUri] int? colors_wrapper_font_size, [FromODataUri] string colors_wrapper_background, [FromODataUri] string colors_wrapper_margin, [FromODataUri] string colors_group, [FromODataUri] int? colors_color1_rgb, [FromODataUri] decimal? colors_color1_brightness, [FromODataUri] string colors_color1_isDark, [FromODataUri] int? colors_color2_hex, [FromODataUri] int? colors_color2_rgb, [FromODataUri] decimal? colors_color2_brightness, [FromODataUri] string colors_color2_isDark, [FromODataUri] int? colors_color3_hex, [FromODataUri] int? colors_color3_rgb, [FromODataUri] decimal? colors_color3_brightness, [FromODataUri] string colors_color3_isDark, [FromODataUri] int? colors_color4_hex, [FromODataUri] int? colors_color4_rgb, [FromODataUri] decimal? colors_color4_brightness, [FromODataUri] string colors_color4_isDark, [FromODataUri] int? colors_color5_hex, [FromODataUri] int? colors_color5_rgb, [FromODataUri] decimal? colors_color5_brightness, [FromODataUri] string colors_color5_isDark)
        {
            this.OnDesignSchemesInsertsDefaultParams(ref colors_body_background, ref colors_body_font, ref colors_body_font_size, ref colors_body_font_color, ref colors_content_text_color, ref colors_content_border_color, ref colors_content_background, ref colors_content_padding, ref colors_content_margin, ref colors_menu_padding, ref colors_menu_font_size, ref colors_menu_background, ref colors_menu_margin, ref colors_header_padding, ref colors_header_font_size, ref colors_header_background, ref colors_header_margin, ref colors_footer_padding, ref colors_footer_font_size, ref colors_footer_background, ref colors_footer_margin, ref colors_wrapper_padding, ref colors_wrapper_font_size, ref colors_wrapper_background, ref colors_wrapper_margin, ref colors_group, ref colors_color1_rgb, ref colors_color1_brightness, ref colors_color1_isDark, ref colors_color2_hex, ref colors_color2_rgb, ref colors_color2_brightness, ref colors_color2_isDark, ref colors_color3_hex, ref colors_color3_rgb, ref colors_color3_brightness, ref colors_color3_isDark, ref colors_color4_hex, ref colors_color4_rgb, ref colors_color4_brightness, ref colors_color4_isDark, ref colors_color5_hex, ref colors_color5_rgb, ref colors_color5_brightness, ref colors_color5_isDark);

            var items = this.context.DesignSchemesInserts.FromSqlRaw("EXEC [dbo].[DesignSchemesInsert] @colors_body_background={0}, @colors_body_font={1}, @colors_body_font_size={2}, @colors_body_font_color={3}, @colors_content_text_color={4}, @colors_content_border_color={5}, @colors_content_background={6}, @colors_content_padding={7}, @colors_content_margin={8}, @colors_menu_padding={9}, @colors_menu_font_size={10}, @colors_menu_background={11}, @colors_menu_margin={12}, @colors_header_padding={13}, @colors_header_font_size={14}, @colors_header_background={15}, @colors_header_margin={16}, @colors_footer_padding={17}, @colors_footer_font_size={18}, @colors_footer_background={19}, @colors_footer_margin={20}, @colors_wrapper_padding={21}, @colors_wrapper_font_size={22}, @colors_wrapper_background={23}, @colors_wrapper_margin={24}, @colors_group={25}, @colors_color1_rgb={26}, @colors_color1_brightness={27}, @colors_color1_isDark={28}, @colors_color2_hex={29}, @colors_color2_rgb={30}, @colors_color2_brightness={31}, @colors_color2_isDark={32}, @colors_color3_hex={33}, @colors_color3_rgb={34}, @colors_color3_brightness={35}, @colors_color3_isDark={36}, @colors_color4_hex={37}, @colors_color4_rgb={38}, @colors_color4_brightness={39}, @colors_color4_isDark={40}, @colors_color5_hex={41}, @colors_color5_rgb={42}, @colors_color5_brightness={43}, @colors_color5_isDark={44}", colors_body_background, colors_body_font, colors_body_font_size, colors_body_font_color, colors_content_text_color, colors_content_border_color, colors_content_background, colors_content_padding, colors_content_margin, colors_menu_padding, colors_menu_font_size, colors_menu_background, colors_menu_margin, colors_header_padding, colors_header_font_size, colors_header_background, colors_header_margin, colors_footer_padding, colors_footer_font_size, colors_footer_background, colors_footer_margin, colors_wrapper_padding, colors_wrapper_font_size, colors_wrapper_background, colors_wrapper_margin, colors_group, colors_color1_rgb, colors_color1_brightness, colors_color1_isDark, colors_color2_hex, colors_color2_rgb, colors_color2_brightness, colors_color2_isDark, colors_color3_hex, colors_color3_rgb, colors_color3_brightness, colors_color3_isDark, colors_color4_hex, colors_color4_rgb, colors_color4_brightness, colors_color4_isDark, colors_color5_hex, colors_color5_rgb, colors_color5_brightness, colors_color5_isDark).ToList().AsQueryable();

            this.OnDesignSchemesInsertsInvoke(ref items);

            return Ok(items);
        }

        partial void OnDesignSchemesInsertsDefaultParams(ref string colors_body_background, ref string colors_body_font, ref int? colors_body_font_size, ref string colors_body_font_color, ref string colors_content_text_color, ref string colors_content_border_color, ref string colors_content_background, ref string colors_content_padding, ref string colors_content_margin, ref string colors_menu_padding, ref int? colors_menu_font_size, ref string colors_menu_background, ref string colors_menu_margin, ref string colors_header_padding, ref int? colors_header_font_size, ref string colors_header_background, ref string colors_header_margin, ref string colors_footer_padding, ref int? colors_footer_font_size, ref string colors_footer_background, ref string colors_footer_margin, ref string colors_wrapper_padding, ref int? colors_wrapper_font_size, ref string colors_wrapper_background, ref string colors_wrapper_margin, ref string colors_group, ref int? colors_color1_rgb, ref decimal? colors_color1_brightness, ref string colors_color1_isDark, ref int? colors_color2_hex, ref int? colors_color2_rgb, ref decimal? colors_color2_brightness, ref string colors_color2_isDark, ref int? colors_color3_hex, ref int? colors_color3_rgb, ref decimal? colors_color3_brightness, ref string colors_color3_isDark, ref int? colors_color4_hex, ref int? colors_color4_rgb, ref decimal? colors_color4_brightness, ref string colors_color4_isDark, ref int? colors_color5_hex, ref int? colors_color5_rgb, ref decimal? colors_color5_brightness, ref string colors_color5_isDark);

        partial void OnDesignSchemesInsertsInvoke(ref IQueryable<ZarenUI.Server.Models.JSONServer.DesignSchemesInsert> items);
    }
}
